### ISSUE TITLE
Blog: Kickstarting a game dev project

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/GodotDevOps#47]
Let's write a post on how to properly get a game dev project off the ground using all the knowledge we've got so far:

- GitHub
  - Creating a repository
  - Inviting collaborators
  - Creating a project board
    - Lining out a healthy workflow
- Git
  - Commit habits
  - Branch habits
  - LFS
- Game dev
  - Test Driven Development
- GitHub actions
  - Automate verification
- Itch.io
  - Setting up a game page
- GitHub Actions revisited
  - Automate release note generation
  - Automate publication

Let's link to relevant resources (for Godot _and_ Unity) if we can. e.g. link to useful YouTube channels, blogs, docs, etc.

## Tasks

- [x] Rough draft written in MarkDown
  - i.e. Section titles and intended content
- [x] First editorial session with Thierry
- [ ] Flesh out draft
  - i.e. Actually write some paragraphs, link to resources
- [ ] Second editorial session with Thierry
- [ ] Final adjustments to draft
- [ ] Last edits by Thierry

## DoD

Blog post available in GitHub repo (can be published to eficode.com)
